# Netlify configuration file

# Build settings
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"

# Redirects and headers
[[redirects]]
  # Redirect all paths to index.html with a 200 status code
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for HTML and JSON
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"