name: Update Market Data

on:
  schedule:
    - cron: '0 4 * * *'  # Run at 4 AM UTC daily
  workflow_dispatch:     # Allow manual triggers

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger data update function
        run: |
          curl -X POST ${{ secrets.NETLIFY_FUNCTION_URL }}/.netlify/functions/scheduled-update
